imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: thumbnails.yml}

parameters:
  web_root: %kernel.root_dir%/../web

framework:
    #esi:             ~
    trusted_proxies: ~
    translator:      { fallback: %locale% }
    secret:          %secret%
    router:          { resource: "%kernel.root_dir%/config/routing.yml" }
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    session:     ~

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    # java: /usr/bin/java
    filters:
        cssrewrite: ~
        # closure:
        #     jar: %kernel.root_dir%/java/compiler.jar
        # yui_css:
        #     jar: %kernel.root_dir%/java/yuicompressor-2.4.2.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        entity_managers:
          default:
            auto_mapping: true
            mappings:
              StofDoctrineExtensionsBundle: ~
            dql:
              string_functions:
                greatest: \Rodger\GalleryBundle\DoctrineExtension\Greatest


jms_security_extra:
    secure_all_services: false

fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: Rodger\UserBundle\Entity\User

stof_doctrine_extensions:
  default_locale: en_US
  orm:
    default:
      tree: true
      timestampable: true
      sluggable: true

