imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.filesystem

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true
    
mink:
  default_session:  goutte
  goutte:           ~
  
doctrine:
  dbal:
    dbname:   %database_name%_test
