liip_imagine:
  driver: imagick
  data_root: %kernel.root_dir%/../uploads/images/

  filter_sets:
    word_thumbnail:
      filters:
        thumbnail: { size: [50, 50], mode: outbound }

    edit:
      filters:
        thumbnail: { size: [800, 2000], mode: inbound, quality: 100, format: png }
    list:
      filters:
        thumbnail: { size: [75, 75], mode: outbound, quality: 70, format: jpg }
    list.small:
      filters:
        thumbnail: { size: [50, 50], mode: inbound, quality: 70, format: jpg }
    list.medium:
      filters:
        thumbnail: { size: [200, 200], mode: outbound, quality: 70, format: jpg }
    resource:
      filters:
        thumbnail: { size: [800, 600], mode: inbound, format: png }

