vich_uploader:
  db_driver: orm
  storage: vich_uploader.storage.file_system
  mappings:
    image:
      uri_prefix: /
      directory_namer: namer.directory
      namer: rodgermd.vichuploader.namer_md5
      upload_destination: %kernel.root_dir%/../uploads/images

liip_imagine:
  driver: imagick
  data_root: %kernel.root_dir%/../uploads/images/
  cache_clearer: false

  filter_sets:
    word_thumbnail:
      filters:
        thumbnail: { size: [50, 50], mode: outbound }

    edit:
      filters:
        thumbnail: { size: [800, 2000], mode: inset, quality: 100, format: png }
    list:
      filters:
        thumbnail: { size: [75, 75], mode: outbound, quality: 70, format: jpg }
    list.small:
      filters:
        thumbnail: { size: [50, 50], mode: inset, quality: 70, format: jpg }
    list.medium:
      filters:
        thumbnail: { size: [200, 200], mode: outbound, quality: 70, format: jpg }
    resource:
      filters:
        thumbnail: { size: [800, 600], mode: inset, format: png }

