services:
  kernel.listener.pre_execute_listener:
    class: Rodger\GalleryBundle\Listener\PreExecuteListener
    tags:
      - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }

  form.type.image_checkbox.addmethod:
    class: Rodger\GalleryBundle\Form\ImageCheckboxType
    tags:
      - { name: form.type, alias: image_checkbox }

  twig.stuff:
    class: Rodger\GalleryBundle\Twig\Stuff
    arguments: [%web_root%, @liip_imagine.templating.helper, @vich_uploader.templating.helper.uploader_helper]
    tags:
      - { name: twig.extension}

  gallery.upload_manager:
    class: Rodger\GalleryBundle\Manager\UploadManager
    arguments: [@service_container]

  namer.directory:
    class: Rodger\GalleryBundle\Namer\DirectoryNamer