<?php

namespace Rodger\GalleryBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AlbumRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlbumRepository extends EntityRepository
{
  /**
   * Prepares QUeryBuilder to show latest albums
   * @param boolean $show_private
   * @return \Doctrine\ORM\QueryBuilder 
   */
  public function getLatestQueryBuilder($show_private = false)
  {
    $qb = $this->createQueryBuilder('a');
    $qb->select('a')->innerJoin('a.Images', 'i');
    if (!$show_private) {
      $qb->where('a.is_private = false AND i.is_private = false');
    }
    $qb->addSelect('GREATEST(a.created_at, i.uploaded_at) sort_date')
       ->orderBy('sort_date', 'desc');
    
    return $qb;
  }
}