<?php

namespace Rodger\GalleryBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagRepository extends EntityRepository
{
  /**
   * Searches Tags like givem
   * @param string $name
   * @return array - Tags
   */
  public function search($name)
  {
    $qb = $this->createQueryBuilder('t');
    return $qb
            ->select('t')
            ->where($qb->expr()->like('u.firstname', $qb->expr()->literal($name . '%')))
            ->execute()
            ->getResult();
  }
  
  /**
   * Gets existing or creates new Tag
   * @return Tag
   */
  public function getOrCreate($name) {
    $tag = $this->find($name);
    if (!$tag) {
      $tag = new Tag();
      $tag->setName($name);
      $this->_em->persist($tag);
    }
    
    return $tag;
  }
}